#!/usr/bin/env python3
"""
Fix missing Vietnamese diacritics in MEKONG_DE_AN_V2_MASTER.md
Skips mermaid/code blocks. Uses word-boundary-aware regex.
"""
import re, os

# ── PHRASE DICTIONARY (longer phrases first for priority) ──
# Only multi-word and safe single-word replacements.
# DANGEROUS single words (tang, den, loi, hieu, moi, chinh, tai, cung) are
# handled ONLY inside multi-word phrases to avoid ambiguity.

REPLACEMENTS = {
    # ═══ 4+ word phrases ═══
    "do chinh xac cao": "độ chính xác cao",
    "gia muc tieu": "giá mục tiêu",
    "ma san pham": "mã sản phẩm",
    "Ma san pham": "Mã sản phẩm",
    "giong mo hinh": "giống mô hình",
    "giam chi phi": "giảm chi phí",
    "kenh doc lap": "kênh độc lập",
    "gia tri khac biet": "giá trị khác biệt",
    "Gia tri khac biet": "Giá trị khác biệt",
    "do chinh xac": "độ chính xác",
    "Do chinh xac": "Độ chính xác",
    "do phan giai": "độ phân giải",
    "Do phan giai": "Độ phân giải",
    "tai su dung": "tái sử dụng",
    "Tai su dung": "Tái sử dụng",
    "gia tri cot loi": "giá trị cốt lõi",
    "Gia tri cot loi": "Giá trị cốt lõi",
    "dong luc tang truong": "động lực tăng trưởng",
    "Dong luc tang truong": "Động lực tăng trưởng",
    "nha cung cap": "nhà cung cấp",
    "Nha cung cap": "Nhà cung cấp",
    "khong can server rieng": "không cần server riêng",
    "khong can may chu rieng": "không cần máy chủ riêng",
    "khong can may chu": "không cần máy chủ",
    "khong can cai": "không cần cài",
    "khong can phan mem rieng": "không cần phần mềm riêng",
    "khong can nguon": "không cần nguồn",
    "khong gioi han dung luong": "không giới hạn dung lượng",
    "khong gioi han": "không giới hạn",
    "khong co tieng Viet": "không có tiếng Việt",
    "khong co uy tin": "không có uy tín",
    "khong the thieu": "không thể thiếu",
    "khong on dinh": "không ổn định",
    "khong can tu van hanh": "không cần tự vận hành",
    "khong phat sinh CAPEX": "không phát sinh CAPEX",
    "chua co BACnet BTL": "chưa có BACnet BTL",
    "chua co uy tin": "chưa có uy tín",
    "co san 100": "có sẵn 100",
    "co the demo truc tiep": "có thể demo trực tiếp",
    "tren cung day chuyen": "trên cùng dây chuyền",

    # ═══ 3-word phrases ═══
    "tang truong": "tăng trưởng",
    "Tang truong": "Tăng trưởng",
    "Phu luc": "Phụ lục",
    "phu luc": "phụ lục",
    "Muc tieu": "Mục tiêu",
    "muc tieu": "mục tiêu",
    "san pham": "sản phẩm",
    "San pham": "Sản phẩm",
    "cong nghe": "công nghệ",
    "Cong nghe": "Công nghệ",
    "nang luong": "năng lượng",
    "Nang luong": "Năng lượng",
    "phat trien": "phát triển",
    "Phat trien": "Phát triển",
    "tai chinh": "tài chính",
    "Tai chinh": "Tài chính",
    "thiet bi": "thiết bị",
    "Thiet bi": "Thiết bị",
    "giai phap": "giải pháp",
    "Giai phap": "Giải pháp",
    "quan ly": "quản lý",
    "Quan ly": "Quản lý",
    "moi truong": "môi trường",
    "Moi truong": "Môi trường",
    "dao tao": "đào tạo",
    "Dao tao": "Đào tạo",
    "xay dung": "xây dựng",
    "Xay dung": "Xây dựng",
    "kiem tra": "kiểm tra",
    "Kiem tra": "Kiểm tra",
    "tich hop": "tích hợp",
    "Tich hop": "Tích hợp",
    "chien luoc": "chiến lược",
    "Chien luoc": "Chiến lược",
    "phan tich": "phân tích",
    "Phan tich": "Phân tích",
    "danh gia": "đánh giá",
    "Danh gia": "Đánh giá",
    "bao cao": "báo cáo",
    "Bao cao": "Báo cáo",
    "nang cap": "nâng cấp",
    "Nang cap": "Nâng cấp",
    "ho tro": "hỗ trợ",
    "Ho tro": "Hỗ trợ",
    "ky thuat": "kỹ thuật",
    "Ky thuat": "Kỹ thuật",
    "van hanh": "vận hành",
    "Van hanh": "Vận hành",
    "giam sat": "giám sát",
    "Giam sat": "Giám sát",
    "dieu khien": "điều khiển",
    "Dieu khien": "Điều khiển",
    "toa nha": "tòa nhà",
    "Toa nha": "Tòa nhà",
    "chieu sang": "chiếu sáng",
    "Chieu sang": "Chiếu sáng",
    "nhiet do": "nhiệt độ",
    "Nhiet do": "Nhiệt độ",
    "dong ho": "đồng hồ",
    "Dong ho": "Đồng hồ",
    "cong suat": "công suất",
    "Cong suat": "Công suất",
    "he thong": "hệ thống",
    "He thong": "Hệ thống",
    "ung dung": "ứng dụng",
    "Ung dung": "Ứng dụng",
    "phan mem": "phần mềm",
    "Phan mem": "Phần mềm",
    "giao dien": "giao diện",
    "Giao dien": "Giao diện",
    "cau hinh": "cấu hình",
    "Cau hinh": "Cấu hình",
    "lap dat": "lắp đặt",
    "Lap dat": "Lắp đặt",
    "nha may": "nhà máy",
    "Nha may": "Nhà máy",
    "chuyen dung": "chuyên dụng",
    "Chuyen dung": "Chuyên dụng",
    "chi phi": "chi phí",
    "Chi phi": "Chi phí",
    "dau tu": "đầu tư",
    "Dau tu": "Đầu tư",
    "hien tai": "hiện tại",
    "Hien tai": "Hiện tại",
    "doi thu": "đối thủ",
    "Doi thu": "Đối thủ",
    "thuong mai": "thương mại",
    "Thuong mai": "Thương mại",
    "bat buoc": "bắt buộc",
    "Bat buoc": "Bắt buộc",
    "quy dinh": "quy định",
    "Quy dinh": "Quy định",
    "thi truong": "thị trường",
    "Thi truong": "Thị trường",
    "thi phan": "thị phần",
    "Thi phan": "Thị phần",
    "canh tranh": "cạnh tranh",
    "Canh tranh": "Cạnh tranh",
    "san xuat": "sản xuất",
    "San xuat": "Sản xuất",
    "nghien cuu": "nghiên cứu",
    "Nghien cuu": "Nghiên cứu",
    "tu dong": "tự động",
    "Tu dong": "Tự động",
    "cong nghiep": "công nghiệp",
    "Cong nghiep": "Công nghiệp",
    "khach hang": "khách hàng",
    "Khach hang": "Khách hàng",
    "tiet kiem": "tiết kiệm",
    "Tiet kiem": "Tiết kiệm",
    "cong trinh": "công trình",
    "Cong trinh": "Công trình",
    "thiet ke": "thiết kế",
    "Thiet ke": "Thiết kế",
    "du an": "dự án",
    "Du an": "Dự án",
    "dien tich": "diện tích",
    "Dien tich": "Diện tích",
    "chung nhan": "chứng nhận",
    "Chung nhan": "Chứng nhận",
    "hop dong": "hợp đồng",
    "Hop dong": "Hợp đồng",
    "dam bao": "đảm bảo",
    "Dam bao": "Đảm bảo",
    "bao tri": "bảo trì",
    "Bao tri": "Bảo trì",
    "day chuyen": "dây chuyền",
    "Day chuyen": "Dây chuyền",
    "dien ap": "điện áp",
    "Dien ap": "Điện áp",
    "dong dien": "dòng điện",
    "Dong dien": "Dòng điện",
    "tro khang": "trở kháng",
    "cam bien": "cảm biến",
    "Cam bien": "Cảm biến",
    "anh sang": "ánh sáng",
    "Anh sang": "Ánh sáng",
    "hien dien": "hiện diện",
    "Hien dien": "Hiện diện",
    "cong tac": "công tắc",
    "Cong tac": "Công tắc",
    "bao chay": "báo cháy",
    "Bao chay": "Báo cháy",
    "dau bao": "đầu báo",
    "Dau bao": "Đầu báo",
    "nut nhan": "nút nhấn",
    "thang may": "thang máy",
    "Thang may": "Thang máy",
    "thang cuon": "thang cuốn",
    "Thang cuon": "Thang cuốn",
    "an toan": "an toàn",
    "An toan": "An toàn",
    "tien ich": "tiện ích",
    "Tien ich": "Tiện ích",
    "bat thuong": "bất thường",
    "Bat thuong": "Bất thường",
    "du doan": "dự đoán",
    "Du doan": "Dự đoán",
    "mo hinh": "mô hình",
    "Mo hinh": "Mô hình",
    "chuyen doi": "chuyển đổi",
    "Chuyen doi": "Chuyển đổi",
    "tu dien": "tủ điện",
    "Tu dien": "Tủ điện",
    "do chinh xac": "độ chính xác",
    "Do chinh xac": "Độ chính xác",
    "phan giai": "phân giải",
    "Phan giai": "Phân giải",
    "do phan giai": "độ phân giải",
    "Do phan giai": "Độ phân giải",
    "nguon": "nguồn",
    "Nguon": "Nguồn",
    "bao ve": "bảo vệ",
    "Bao ve": "Bảo vệ",
    "chong set": "chống sét",
    "Chong set": "Chống sét",
    "cho phep": "cho phép",
    "Cho phep": "Cho phép",
    "mo rong": "mở rộng",
    "Mo rong": "Mở rộng",
    "ket noi": "kết nối",
    "Ket noi": "Kết nối",
    "toi da": "tối đa",
    "Toi da": "Tối đa",
    "toi uu": "tối ưu",
    "Toi uu": "Tối ưu",
    "doc lap": "độc lập",
    "Doc lap": "Độc lập",
    "da nang": "đa năng",
    "Da nang": "Đa năng",
    "thoi gian": "thời gian",
    "Thoi gian": "Thời gian",
    "giam chi phi": "giảm chi phí",
    "hieu suat": "hiệu suất",
    "Hieu suat": "Hiệu suất",
    "hieu qua": "hiệu quả",
    "Hieu qua": "Hiệu quả",
    "dong thoi": "đồng thời",
    "Dong thoi": "Đồng thời",
    "thuc hien": "thực hiện",
    "Thuc hien": "Thực hiện",
    "duoc": "được",
    "tieng Viet": "tiếng Việt",
    "tieng Anh": "tiếng Anh",
    "khong gian": "không gian",
    "Khong gian": "Không gian",
    "kinh nghiem": "kinh nghiệm",
    "Kinh nghiem": "Kinh nghiệm",
    "giao thuc": "giao thức",
    "Giao thuc": "Giao thức",
    "truyen thong": "truyền thông",
    "Truyen thong": "Truyền thông",
    "dieu hoa": "điều hòa",
    "Dieu hoa": "Điều hòa",
    "khong khi": "không khí",
    "Khong khi": "Không khí",
    "ap suat": "áp suất",
    "Ap suat": "Áp suất",
    "mat bang": "mặt bằng",
    "Mat bang": "Mặt bằng",
    "do am": "độ ẩm",
    "thong bao": "thông báo",
    "Thong bao": "Thông báo",
    "khach san": "khách sạn",
    "Khach san": "Khách sạn",
    "benh vien": "bệnh viện",
    "Benh vien": "Bệnh viện",
    "van phong": "văn phòng",
    "Van phong": "Văn phòng",
    "truong hoc": "trường học",
    "Truong hoc": "Trường học",
    "phan khuc": "phân khúc",
    "Phan khuc": "Phân khúc",
    "tam trung": "tầm trung",
    "Tam trung": "Tầm trung",
    "dau thau": "đấu thầu",
    "Dau thau": "Đấu thầu",
    "thuc te": "thực tế",
    "Thuc te": "Thực tế",
    "mang luoi": "mạng lưới",
    "Mang luoi": "Mạng lưới",
    "gio tri": "giá trị",
    "gia tri": "giá trị",
    "Gia tri": "Giá trị",
    "co san": "có sẵn",
    "Co san": "Có sẵn",
    "on dinh": "ổn định",
    "On dinh": "Ổn định",
    "loi the": "lợi thế",
    "Loi the": "Lợi thế",
    "doi tuong": "đối tượng",
    "Doi tuong": "Đối tượng",
    "noi bo": "nội bộ",
    "Noi bo": "Nội bộ",
    "ha tang": "hạ tầng",
    "Ha tang": "Hạ tầng",
    "uu dai": "ưu đãi",
    "Uu dai": "Ưu đãi",
    "tac dong": "tác động",
    "Tac dong": "Tác động",
    "ban le": "bán lẻ",
    "Ban le": "Bán lẻ",
    "thuong luong": "thương lượng",
    "Thuong luong": "Thương lượng",
    "rao can": "rào cản",
    "bat dau": "bắt đầu",
    "Bat dau": "Bắt đầu",
    "chuyen gia": "chuyên gia",
    "Chuyen gia": "Chuyên gia",
    "tuyen dung": "tuyển dụng",
    "Tuyen dung": "Tuyển dụng",
    "bo sung": "bổ sung",
    "Bo sung": "Bổ sung",
    "rui ro": "rủi ro",
    "Rui ro": "Rủi ro",
    "muc do": "mức độ",
    "Muc do": "Mức độ",
    "bien phap": "biện pháp",
    "Bien phap": "Biện pháp",
    "giam thieu": "giảm thiểu",
    "Giam thieu": "Giảm thiểu",
    "lo trinh": "lộ trình",
    "Lo trinh": "Lộ trình",
    "nhan dinh": "nhận định",
    "Nhan dinh": "Nhận định",
    "hop ly": "hợp lý",
    "Hop ly": "Hợp lý",
    "qua tai": "quá tải",
    "kien truc": "kiến trúc",
    "Kien truc": "Kiến trúc",
    "chat luong": "chất lượng",
    "Chat luong": "Chất lượng",
    "dung chung": "dùng chung",
    "Dung chung": "Dùng chung",
    "hang loat": "hàng loạt",
    "Hang loat": "Hàng loạt",
    "pho bien": "phổ biến",
    "Pho bien": "Phổ biến",
    "chuyen sang": "chuyển sang",
    "dien thoai": "điện thoại",
    "Dien thoai": "Điện thoại",
    "xu ly": "xử lý",
    "Xu ly": "Xử lý",
    "luu tru": "lưu trữ",
    "Luu tru": "Lưu trữ",
    "du lieu": "dữ liệu",
    "Du lieu": "Dữ liệu",
    "lich su": "lịch sử",
    "Lich su": "Lịch sử",
    "do thi": "đồ thị",
    "truc tiep": "trực tiếp",
    "Truc tiep": "Trực tiếp",
    "tu xa": "từ xa",
    "Tu xa": "Từ xa",
    "ban quyen": "bản quyền",
    "Ban quyen": "Bản quyền",
    "cap phep": "cấp phép",
    "Cap phep": "Cấp phép",
    "gioi thieu": "giới thiệu",
    "Gioi thieu": "Giới thiệu",
    "tham gia": "tham gia",  # already correct
    "dien tu": "điện tử",
    "Dien tu": "Điện tử",
    "so luong": "số lượng",
    "So luong": "Số lượng",
    "mien phi": "miễn phí",
    "Mien phi": "Miễn phí",
    "de xuat": "đề xuất",
    "De xuat": "Đề xuất",
    "co hoi": "cơ hội",
    "Co hoi": "Cơ hội",
    "nhu cau": "nhu cầu",
    "Nhu cau": "Nhu cầu",
    "su dung": "sử dụng",
    "Su dung": "Sử dụng",
    "phu hop": "phù hợp",
    "Phu hop": "Phù hợp",
    "don gian": "đơn giản",
    "Don gian": "Đơn giản",
    "tang them": "tăng thêm",
    "tieu bieu": "tiêu biểu",
    "Tieu bieu": "Tiêu biểu",
    "thuoc tinh": "thuộc tính",
    "thuc day": "thúc đẩy",
    "Thuc day": "Thúc đẩy",
    "nhan su": "nhân sự",
    "Nhan su": "Nhân sự",
    "hong hoc": "hỏng hóc",
    "Hong hoc": "Hỏng hóc",
    "dung luong": "dung lượng",
    "Dung luong": "Dung lượng",
    "tren nen": "trên nền",
    "Tren nen": "Trên nền",
    "phan cung": "phần cứng",
    "Phan cung": "Phần cứng",
    "tai su dung": "tái sử dụng",
    "Tai su dung": "Tái sử dụng",
    "gia ban": "giá bán",
    "Gia ban": "Giá bán",
    "giong mo hinh": "giống mô hình",
    "ap dung": "áp dụng",
    "Ap dung": "Áp dụng",
    "ban hang": "bán hàng",
    "Ban hang": "Bán hàng",
    "quy mo": "quy mô",
    "Quy mo": "Quy mô",
    "co ban": "cơ bản",
    "Co ban": "Cơ bản",
    "tham chieu": "tham chiếu",
    "Tham chieu": "Tham chiếu",
    "uoc tinh": "ước tính",
    "Uoc tinh": "Ước tính",
    "cong cu": "công cụ",
    "Cong cu": "Công cụ",
    "lap trinh": "lập trình",
    "Lap trinh": "Lập trình",
    "gia muc tieu": "giá mục tiêu",
    "Gia muc tieu": "Giá mục tiêu",
    "so kenh": "số kênh",
    "So kenh": "Số kênh",
    "giao tiep": "giao tiếp",
    "Giao tiep": "Giao tiếp",
    "tin hieu": "tín hiệu",
    "Tin hieu": "Tín hiệu",
    "gioi han": "giới hạn",
    "Gioi han": "Giới hạn",
    "kenh doc lap": "kênh độc lập",
    "dong co": "động cơ",
    "Dong co": "Động cơ",
    "bien tan": "biến tần",
    "Bien tan": "Biến tần",
    "chuyen mach": "chuyển mạch",
    "thuong": "thường",
    "khong": "không",
    "cung": "cùng",
    "tren": "trên",
    "duoi": "dưới",
    "truoc": "trước",
    "moi": "mỗi",
    "voi": "với",
    "cho": "cho",
    "cua": "của",
    "nhung": "nhưng",
    "chinh": "chính",
    "ngoai": "ngoài",
    "tuong ung": "tương ứng",
    "Tuong ung": "Tương ứng",
    "dong thoi": "đồng thời",
    "tiem nang": "tiềm năng",
    "Tiem nang": "Tiềm năng",
    "thanh phan": "thành phần",
    "Thanh phan": "Thành phần",
    "chuan": "chuẩn",
    "Chuan": "Chuẩn",
    "co dinh": "cố định",
    "Co dinh": "Cố định",
    "hoa mang": "hòa mạng",
    "tong cong": "tổng cộng",
    "Tong cong": "Tổng cộng",
    "vuot xa": "vượt xa",
    "kha nang": "khả năng",
    "Kha nang": "Khả năng",
    "ben ngoai": "bên ngoài",
    "Ben ngoai": "Bên ngoài",
    "thong nhat": "thống nhất",
    "Thong nhat": "Thống nhất",
    "phan loai": "phân loại",
    "Phan loai": "Phân loại",
    # Single common words
    "loai": "loại",
    "Loai": "Loại",
    "diem": "điểm",
    "Diem": "Điểm",
    "nuoc": "nước",
    "Nuoc": "Nước",
    "dien": "điện",
    "Dien": "Điện",
    "tang": "tầng",
    "Tang": "Tầng",
    "tru cot": "trụ cột",
    "Tru cot": "Trụ cột",
    "cot": "cột",
    "quat": "quạt",
    "bom": "bơm",
    "Bom": "Bơm",
    "den": "đèn",
    "ma san pham": "Mã sản phẩm",
    "Ma san pham": "Mã sản phẩm",
    "buoc": "bước",
    "Buoc": "Bước",
    "loi": "lỗi",
    "hieu": "hiệu",
    "Hieu": "Hiệu",
}

# Compile regex patterns - sort by length descending to match longer phrases first
patterns = []
for old in sorted(REPLACEMENTS.keys(), key=len, reverse=True):
    new = REPLACEMENTS[old]
    if old == new:
        continue  # Skip identical replacements
    # Use word boundaries, but be careful with Vietnamese
    pat = re.compile(r'(?<![a-zA-ZáàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵđÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬÉÈẺẼẸÊẾỀỂỄỆÍÌỈĨỊÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÚÙỦŨỤƯỨỪỬỮỰÝỲỶỸỴĐ])' + re.escape(old) + r'(?![a-zA-ZáàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵđÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬÉÈẺẼẸÊẾỀỂỄỆÍÌỈĨỊÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÚÙỦŨỤƯỨỪỬỮỰÝỲỶỸỴĐ])')
    patterns.append((pat, new, old))

def fix_line(line):
    """Apply all diacritics fixes to a single line."""
    result = line
    for pat, new, old in patterns:
        result = pat.sub(new, result)
    return result

def main():
    filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'MEKONG_DE_AN_V2_MASTER.md')
    
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    total_changes = 0
    changed_lines = []
    
    for i, line in enumerate(lines):
        # Skip mermaid code blocks
        newline = fix_line(line)
        if newline != line:
            total_changes += 1
            changed_lines.append(i + 1)
            lines[i] = newline
    
    # Write back
    with open(filepath, 'w', encoding='utf-8', newline='') as f:
        f.writelines(lines)
    
    print(f"Fixed {total_changes} lines")
    if changed_lines:
        print(f"Changed lines: {changed_lines[:50]}{'...' if len(changed_lines) > 50 else ''}")

if __name__ == '__main__':
    main()
