%%{init: {'theme': 'base'}}%%
xychart-beta
    title "Revenue Mix Evolution (%)"
    x-axis ["Y1", "Y5", "Y10", "Y20"]
    y-axis "Tỷ trọng %" 0 --> 100
    bar [57, 53, 43, 35]
    bar [17, 24, 28, 27]
    bar [26, 24, 30, 38]