graph TD
    CEO["CEO / Tổng Giám đốc"]
    
    CEO --> CFO["CFO<br/>Tài chính"]
    CEO --> CTO["CTO<br/>Công nghệ"]
    CEO --> COO["COO<br/>Vận hành"]
    CEO --> CSO["CSO<br/>Bán hàng"]
    
    CTO --> IoT["Giám đốc<br/>IoT/Robot<br/>(Khối C)"]
    CTO --> RD["Giám đốc<br/>R&D"]
    
    COO --> CNC["Giám đốc<br/>CNC/MPMC<br/>(Khối B)"]
    COO --> DC["Giám đốc<br/>DC/MACC<br/>(Khối A)"]
    COO --> QC["Giám đốc<br/>QA/QC"]
    COO --> HR["Giám đốc<br/>Nhân sự"]
    
    IoT --> SW["Nhóm<br/>Phần mềm"]
    IoT --> HW["Nhóm<br/>Phần cứng"]
    IoT --> SMT["Nhóm<br/>SMT"]
    IoT --> ASSY["Nhóm<br/>Assembly"]
    
    CNC --> PROG["Nhóm<br/>CAD/CAM"]
    CNC --> MACH["Nhóm<br/>Vận hành máy"]
    CNC --> TOOL["Nhóm<br/>Tooling"]
    
    DC --> NOC["Nhóm<br/>NOC 24/7"]
    DC --> INFRA["Nhóm<br/>Hạ tầng"]
    DC --> SEC["Nhóm<br/>Security"]