graph TB
    PM["Plant Manager CNC<br/>1 nguoi"] --> ENG["Engineering Manager<br/>1 nguoi"]
    PM --> PROD["Production Manager<br/>1 nguoi"]
    PM --> QA["Quality Manager<br/>1 nguoi"]
    PM --> SALES["Sales/BD Manager<br/>1 nguoi"]
    PM --> ADM["Admin Manager<br/>1 nguoi"]
    ENG --> CAD["CAD/CAM Eng<br/>4-6 nguoi"]
    ENG --> PE["Process Eng<br/>2-3 nguoi"]
    PROD --> OPS["CNC Operators<br/>15-25 nguoi"]
    PROD --> ST["Setup Tech<br/>3-5 nguoi"]
    QA --> QC["QA/QC<br/>4-6 nguoi"]
    QA --> CMM["CMM Op<br/>2-3 nguoi"]
    SALES --> BD["BD Exec<br/>2-3 nguoi"]