pie title Phân bổ CAPEX theo Nhóm chức năng
    "Pháp lý + Site" : 6.8
    "Xây dựng 3 công trình" : 26.8
    "M&E + PCCC" : 8.4
    "Nội thất + Solar" : 3.0
    "Thiết bị sản xuất" : 29.1
    "DC Nội bộ" : 10.0
    "QA + Software" : 4.5
    "Vốn lưu động" : 8.4
    "Dự phòng" : 3.0